### ISSUE TITLE
Invitation codes for deployed software

### ISSUE THREAD

**Issue by wizzard0** [Evgenus/spa#28]
Make an option to specify "invitation code" when building, so SPA would then encrypt files with AES, and show a simple dialog box before loading files.
Note this means we'll store encrypted files in localstorage and hashes needs to be similarly calculated from encrypted versions.

Also, as a matter of obfuscation, modules can be renamed to "module1","module2" etc then.

**Comment by Evgenus** [comment]
This issue could be implemented elsewhere cause it is not common for builder use-cases.
