### ISSUE TITLE
why amd module should return anything?!

### ISSUE THREAD

**Issue by wizzard0** [Evgenus/spa#60]
AMDReturnsNothingError: AMD module `event` returns nothing. Should return empty object!

**Comment by wizzard0** [comment]
if it returns nothing and requires exports then it must've filled that exports object.

**Comment by wizzard0** [comment]
also valid for TS-generated amd modules

**Comment by Evgenus** [comment]
> if it returns nothing and requires exports then it must've filled that exports object.

Please provide some code example of described behavior, so I could reproduce this in test case

**Comment by wizzard0** [comment]
define(function(require,exports,module){
exports.xxx =yy;
});
