### ISSUE TITLE
need an option to pass window to module unchanged

### ISSUE THREAD

**Issue by wizzard0** [Evgenus/spa#64]
React, sjcl entropy collector, etc etc.

**Comment by wizzard0** [comment]
getrandomvalues in ff

**Comment by Evgenus** [comment]
I'd rather make my wrapper much better like suggested here https://blog.javascripting.com/2014/05/19/wrapping-the-dom-window-object/ and here https://blog.javascripting.com/2014/05/27/dom-window-wrapper-update/
