### ISSUE TITLE
[regression] Enabling encryption overwrites source files

### ISSUE THREAD

**Issue by wizzard0** [Evgenus/spa#71]
path is not relative to build path for some reason

**Comment by wizzard0** [comment]
why is it even allowed to write outside of build btw?

**Comment by Evgenus** [comment]
there is no such thing as `build path` in spa. there are separate locations for manifest and other output files. please specify your problem more precisely.

**Comment by wizzard0** [comment]
oops i meant root path.

**Comment by Evgenus** [comment]
reproduced https://gist.github.com/Evgenus/060edc0bebfa8672ad48
