### ISSUE TITLE
Maybe use node-precinct to automatically choose the right detective?

### ISSUE THREAD

**Issue by mrjoelkemp** [Evgenus/spa#78]
Replace this https://github.com/Evgenus/spa/blob/master/lib/index.js#L611 with precinct usage.

I created https://github.com/mrjoelkemp/node-precinct for this purpose. Basically, you just forget about the module type and get the dependencies. This also brings out-of-the-box support for ES6 and SASS dependency detection without cluttering your application code.

Might help.

**Comment by Evgenus** [comment]
What about this line https://github.com/Evgenus/spa/blob/master/lib/index.js#L604 ? Also I need type of the module to be stored for use in runtime https://github.com/Evgenus/spa/blob/master/lib/assets/loader.js#L746 . `node-precinct` is nice generalization but I need much more than simply dependencies list.

Thanks, anyway.

**Comment by mrjoelkemp** [comment]
Understood. Lots of cool stuff in spa by the way. Great job!
